In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import mlflow 
import dagshub

In [3]:
import dagshub
dagshub.init(repo_owner='akashkangule18', repo_name='SWIGGI-DELIVERY-TIME-PREDICTION', mlflow=True)

Accessing as akashkangule18

Initialized MLflow to track repo "akashkangule18/SWIGGI-DELIVERY-TIME-PREDICTION"

Repository akashkangule18/SWIGGI-DELIVERY-TIME-PREDICTION initialized!

In [4]:
data = pd.read_csv("../data/raw/uncleaned_swiggy (1).xls")
data.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [5]:
df = data.copy()

In [6]:
# # renames the cols

df.rename(columns = {'Delivery_person_ID':'rider_id',
                     'Delivery_person_Age':'age',
                     'Delivery_person_Ratings':'rating',
                     'Restaurant_latitude':'rest_lat',
                     'Restaurant_longitude':'rest_long',
                     'Delivery_location_latitude':'destination_lat',
                     'Delivery_location_longitude':'destination_long',
                     'Order_Date':'order_date',
                     'Time_Orderd':'order_time',
                     'Time_Order_picked':'order_picked_time',
                     'Weatherconditions':'weather_cond',
                     'Road_traffic_density':'traffic',
                     'Vehicle_condition':'vehicle_cond',
                     'Type_of_order':'order_type',
                     'Type_of_vehicle':'vehicle_type',
                     'multiple_deliveries':'multiple_orders',
                     'Festival':'festival',
                     'City':'city_type',
                     'Time_taken(min)':'delivery_time'
                    }, inplace = True
         )

In [7]:
# lowering all the values  and removing al  the unwnated spaces like trailing and leading spaces in all columns
def lower(column):
    return column.lower().strip()

In [8]:
df['rider_id'] = df['rider_id'].apply(lower)
df['weather_cond'] = df['weather_cond'].apply(lower)
df['traffic'] = df['traffic'].apply(lower)
df['order_type'] = df['order_type'].apply(lower)
df['vehicle_type'] = df['vehicle_type'].apply(lower)
df['festival'] = df['festival'].apply(lower)
df['city_type'] = df['city_type'].apply(lower)

In [9]:
# fixing the nan values from the data from all the columns

# for age
df['age']= df['age'].replace('NaN ', np.nan)

# for rating
df['rating']= df['rating'].replace('NaN ', np.nan)

# for order time
df['order_time']= df['order_time'].replace('NaN ', np.nan)

# for order date
df['order_date']= df['order_date'].replace('nan', np.nan)

# for order picked time
df['order_picked_time']= df['order_picked_time'].replace('NaN ', np.nan)

# for traffic
df['traffic']= df['traffic'].replace('nan', np.nan)

# for vaehical condotion
df['vehicle_cond']= df['vehicle_cond'].replace('NaN ', np.nan)

# for order typpe
df['order_type']= df['order_type'].replace('nan', np.nan)

# for vehicle type
df['vehicle_type']= df['vehicle_type'].replace('nan', np.nan)

# for multiple orders
df['multiple_orders']= df['multiple_orders'].replace('NaN ', np.nan)

# for festivel
df['festival']= df['festival'].replace('nan', np.nan)

# for city type
df['city_type']= df['city_type'].replace('nan', np.nan)

In [10]:
# for weather column
df['weather_cond']= df['weather_cond'].str.split().str.get(1)
df['weather_cond']= df['weather_cond'].replace('nan',np.nan)

In [11]:
# for delivery time
df['delivery_time'] = df['delivery_time'].str.split().str.get(1)

In [12]:
# Changing datatypes
df['age'] = df['age'].astype('float')
df['rating'] = df['rating'].astype('float')
df['multiple_orders'] = df['multiple_orders'].astype(float)


# for datetime columns
df['order_date'] = pd.to_datetime(df['order_date'],dayfirst=True)
df['order_time'] = pd.to_datetime(df['order_time'], format='%H:%M:%S')
df['order_picked_time'] = pd.to_datetime(df['order_picked_time'], format='%H:%M:%S')

# with output column
df['delivery_time'] = df['delivery_time'].astype('int')

In [13]:
df['city_name'] = df['rider_id'].str.split('res').str.get(0)

In [14]:
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name()
df['day'] = df['order_date'].dt.day_name()

In [15]:
# creating the weekend column
def  weekend(column):
    if column == 'Saturday' or column == 'Sunday':
        return 1
    else:
        return 0


df['weekend']= df['day'].apply(weekend)

In [16]:
# now extracting hours and miniuts form the order time and order picked time
# creating new column such order_picked_dur. it will describe that after how many miniuts order was picked
# and again creating time period such as morning, afternon, evening and night

df['ordered_hour'] = df['order_time'].dt.hour
df['ordered_miniut'] = df['order_time'].dt.minute
df['order_picked_time_minute'] = df['order_picked_time'].dt.minute

# new column order_picked_dura
df['order_picked_in_minute'] = df['order_picked_time_minute'] - df['ordered_miniut']


# new column time duration
def time(hour):

    if hour  < 12:
        return 'morning'
    elif hour <  17:
        return 'afternoon'
    elif hour < 21:
        return 'evening'
    else:
        return 'night'


df['time_duration'] = df['ordered_hour'].apply(time)

In [17]:
# now calculating distance between restarunts and destination form the lattiude adn longitude
# but before that removin nan values from this columns for the clean approach

new_df = df.dropna(subset =['rest_lat','rest_long','destination_lat','destination_long'])

In [18]:
# new_column such as distance

def haversine(lat1, lon1, lat2, lon2):
    # Earth radius in km
    R = 6371

    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)
    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))

    return R * c

new_df = df.dropna(subset=[
    'rest_lat','rest_long','destination_lat','destination_long'
]).copy()

new_df['distance_km'] = haversine(
    new_df['rest_lat'],
    new_df['rest_long'],
    new_df['destination_lat'],
    new_df['destination_long']
).round(2)

In [19]:
# # now again cleanig the dataset
# # removing unwnated cols
new_df.drop(columns=['rest_lat','rest_long','destination_lat','destination_long','order_date','order_time','order_picked_time', 'year','order_picked_time_minute'], inplace = True)

In [20]:
# and again therr are some negative values in order_pick in minute so fixing the negative values
new_df['order_picked_in_minute'] = np.where(
    new_df['order_picked_in_minute'] < 0,
    new_df['order_picked_in_minute'] + 60,
    new_df['order_picked_in_minute']
)


# again need to convert all the categorical values into lower
new_df['month_name'] = new_df['month_name'].apply(lower)
new_df['day'] = new_df['day'].apply(lower)

In [21]:
# again creating new coulumn as distnce route
def route(distance):
    if distance < 5:
        return 'short'
    elif distance > 5 and distance < 10:
        return 'medium'
    else :
        return 'long'

new_df['distance_route']  = new_df['distance_km'].apply(route)

In [22]:
new_df.head()

,ID,rider_id,age,rating,weather_cond,traffic,vehicle_cond,order_type,vehicle_type,multiple_orders,...,month,month_name,day,weekend,ordered_hour,ordered_miniut,order_picked_in_minute,time_duration,distance_km,distance_route
0,0x4607,indores13del02,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,...,3,march,saturday,1,11.0,30.0,15.0,morning,3.03,short
1,0xb379,bangres18del02,34.0,4.5,stormy,jam,2,snack,scooter,1.0,...,3,march,friday,0,19.0,45.0,5.0,evening,20.18,long
2,0x5d6d,bangres19del01,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,...,3,march,saturday,1,8.0,30.0,15.0,morning,1.55,short
3,0x7a6a,coimbres13del02,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,...,4,april,tuesday,0,18.0,0.0,10.0,evening,7.79,medium
4,0x70a2,chenres12del01,32.0,4.6,cloudy,high,1,snack,scooter,1.0,...,3,march,saturday,1,13.0,30.0,15.0,afternoon,6.21,medium

In [23]:
# dropping mentioned columns
new_df.drop(columns =['time_duration','ordered_miniut','order_picked_in_minute','month_name','day','order_type','distance_route'],inplace = True)

In [24]:
# checking for null values
new_df.isnull().sum()

ID                    0
rider_id              0
age                1854
rating             1908
weather_cond        616
traffic             601
vehicle_cond          0
vehicle_type          0
multiple_orders     993
festival            228
city_type          1200
delivery_time         0
city_name             0
month                 0
weekend               0
ordered_hour       1731
distance_km           0
dtype: int64

In [ ]:
# dropping the null values beacuse we ran two experiments and experiment with droppping null values ig giving the better results as compare to 
# null values imputation
new_df.dropna(inplace = True)

In [26]:
new_df.drop(columns = ['rider_id','ID'], inplace=True)

In [27]:
new_df.isnull().sum()

age                0
rating             0
weather_cond       0
traffic            0
vehicle_cond       0
vehicle_type       0
multiple_orders    0
festival           0
city_type          0
delivery_time      0
city_name          0
month              0
weekend            0
ordered_hour       0
distance_km        0
dtype: int64

In [51]:
# seperating data 
X = new_df.drop(columns="delivery_time")
y = new_df['delivery_time']

# spliting data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)

# seperating numerical and categorical columns
num_cols = X.select_dtypes(include=['int64','float64','int32']).columns
ohe_cols = ['weather_cond', 'vehicle_type', 'festival', 'city_type','city_name']
ord_cols = ['traffic']

# getting necessary libraries
from sklearn.preprocessing import RobustScaler, PowerTransformer,OrdinalEncoder,OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score, mean_absolute_error


# ordinal encoder
ord_encoder = OrdinalEncoder(
    categories=[['low','jam','medium','high']],
    handle_unknown= "use_encoded_value",
    unknown_value= -1
)

# buiilding pipeline
num_pipe = Pipeline([
    ('transformer',PowerTransformer(method="yeo-johnson")),
    ('scaler',RobustScaler())
])

ord_pipe = Pipeline([
    ('ord_enc',ord_encoder)
])

ohe_pipe = Pipeline([
    ('ohe_encoder',OneHotEncoder(drop='first',handle_unknown='ignore',sparse_output=False))
])

transformer = ColumnTransformer([
    ('num',num_pipe,num_cols),
    ('ord',ord_pipe,ord_cols),
    ('ohe',ohe_pipe,ohe_cols)
])

pipeline = Pipeline([
    ('preprocess',transformer),
    ('regressor',XGBRegressor())
])


pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('transformer',
                                                                   PowerTransformer()),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  Index(['age', 'rating', 'vehicle_cond', 'multiple_orders', 'month', 'weekend',
       'ordered_hour', 'distance_km'],
      dtype='object')),
                                                 ('ord',
                                                  Pipeline(steps=[('ord_enc',
                                                                   OrdinalEncoder(categories=[['low',
                                                                                               'jam',
                                                                                               'medium'...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [52]:
# mkaing clone of this pipeline as base pipeline
from sklearn.base import clone
from sklearn.model_selection import cross_val_score
base_pipeline = clone(pipeline)

base_pipeline

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('transformer',
                                                                   PowerTransformer()),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  Index(['age', 'rating', 'vehicle_cond', 'multiple_orders', 'month', 'weekend',
       'ordered_hour', 'distance_km'],
      dtype='object')),
                                                 ('ord',
                                                  Pipeline(steps=[('ord_enc',
                                                                   OrdinalEncoder(categories=[['low',
                                                                                               'jam',
                                                                                               'medium'...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [61]:

import warnings
warnings.filterwarnings('ignore')

In [ ]:
mlflow.set_experiment('Exp-3 comparing multiple regressor models with hyperparameters tunning')

with mlflow.start_run(run_name = "regressor models with hyperparameters tunning"):

        # using optuna

        import optuna

        def objective(trial):
            model_name = trial.suggest_categorical('model',['RFR','DTR','XGBR','LGBMR'])

            # runnig if else conditions
            if model_name == 'RFR':
                model = RandomForestRegressor(
                    n_estimators= trial.suggest_int('n_estimators',100,300),
                    max_depth= trial.suggest_int('max_depth',3,7),
                    min_samples_split= trial.suggest_int('min_samples_split',2,5),
                    min_samples_leaf= trial.suggest_int('min_sample_leaf',10,50),
                    min_impurity_decrease= trial.suggest_float('min_impurity_decrease',0.01,0.1),
                    n_jobs=-1
                )


            elif model_name == 'DTR':
                model = DecisionTreeRegressor(
                    max_depth= trial.suggest_int('max_depth',2,7),
                    min_samples_split= trial.suggest_int('min_samples_split',2,5),
                    min_samples_leaf= trial.suggest_int('min_samples_float',10,50),
                    min_impurity_decrease= trial.suggest_float('min_impurity_decrease',0.01,0.1)
                )

            elif model_name == 'XGBR':
                model = XGBRegressor(
                    n_estimators = trial.suggest_int('n_estimators',100,300),
                    max_depth = trial.suggest_int('max_depth',2,7),
                    learning_rate = trial.suggest_float('learning_rate',0.05,0.1),
                    min_child_weight = trial.suggest_int('min_child_weight',3,10),
                    subsample = trial.suggest_float('sub_sample',0.5,1),
                    colsample_bytree = trial.suggest_float('colsample_bytree',0.5,1),
                    gamma = trial.suggest_float('gamma',0.1,0.5)
                )

            else:
                model = LGBMRegressor(
                    num_leaves=trial.suggest_int('num_leaves', 20, 100),
                    min_child_samples = trial.suggest_int('min_child_samples',10, 50),
                    max_depth=trial.suggest_int('max_depth', 1, 15),
                    learning_rate=trial.suggest_float('learning_rate', 0.01, 0.1),
                    n_estimators=500,
                    subsample=trial.suggest_float('subsample', 0.5, 1.0),
                    colsample_bytree=trial.suggest_float('colsample_bytree', 0.5, 1.0),
                    reg_alpha=trial.suggest_float('reg_alpha', 0.0, 1.0),
                    reg_lambda=trial.suggest_float('reg_lambda', 0.0, 1.0),
                    random_state=42,
                    n_jobs=-1,
                    verbose = -1
                )


            # again clome the base pipelinne
            new_pipe = clone(base_pipeline)
            new_pipe.set_params(
                regressor = model
            )

            
            scores = cross_val_score(
                new_pipe,
                X_train,
                y_train,
                cv = 5,
                scoring= 'neg_mean_absolute_error'
            )

            return -scores.mean()
        
        
        # creating optuna study
        study = optuna.create_study(direction='minimize')
        study.optimize(objective, n_trials=30)       

        # fetching best parametrs and its value
        print('best_params: ', study.best_params)
        print('best value: ', study.best_value)

        best_params = study.best_params.copy()
        best_params.pop("model")

        # building the final model
        final_model = LGBMRegressor(
            **best_params,
            n_estimators=500,
            random_state=42,
            n_jobs=-1,
            verbose=-1
        )

        # cloning the base pipeline
        LGRregressor = clone(base_pipeline)
        LGRregressor.set_params(
             regressor = final_model
        )

        LGRregressor.fit(X_train,y_train)

        y_train_pred = LGRregressor.predict(X_train)
        y_test_pred = LGRregressor.predict(X_test)

        # fetching the results
        train_mae = mean_absolute_error(y_train,y_train_pred)
        test_mae = mean_absolute_error(y_test,y_test_pred)
        train_r2 = r2_score(y_train,y_train_pred)
        test_r2 = r2_score(y_test,y_test_pred)

        # logging optuna parameters
        mlflow.log_param("n_trials", 30)
        mlflow.log_params(study.best_params)
        mlflow.log_param('optuna_best_trial',study.best_trial.number)


        # logging metrics
        mlflow.log_metric('train_mae',train_mae)
        mlflow.log_metric('optuna_best_mae',study.best_value)
        mlflow.log_metric('train_r2',train_r2)
        mlflow.log_metric('test_mae',test_mae)
        mlflow.log_metric('test_r2',test_r2)

        # logging file
        mlflow.log_artifact("Swiggy-Exp3.ipynb")

        # training data
        train_df = X_train.copy()
        train_df['delivery_time'] = y_train
        train_data = train_df
        train_data = mlflow.data.from_pandas(train_data)

        # testing data
        test_df = X_test.copy()
        test_df['delivery_time'] = y_test
        test_data = test_df
        test_data = mlflow.data.from_pandas(test_data)

        # logging data
        mlflow.log_input(train_data, context= "training dataset")
        mlflow.log_input(test_data, context= 'testing dataset')

        # signature
        signature = mlflow.models.infer_signature(X_train,LGRregressor.predict(X_train))

        # log model
        mlflow.sklearn.log_model(
             sk_model=LGRregressor,
             name='LightgbmRegressor',
             signature= signature,
             serialization_format= mlflow.sklearn.SERIALIZATION_FORMAT_CLOUDPICKLE
        )



        print("training mean absolute error: ", train_mae)
        print("testing mean absolute error: ",test_mae)
        print("training r2_score: ",train_r2)
        print('testing r2_score', test_r2)

2026/06/26 17:34:49 INFO mlflow.tracking.fluent: Experiment with name 'Exp-3 comparing multiple regressor models with hyperparameters tunning' does not exist. Creating a new experiment.
[I 2026-06-26 17:34:51,531] A new study created in memory with name: no-name-55bc4dbe-69b8-4356-b4f3-0e6a3277d468
[I 2026-06-26 17:34:59,883] Trial 0 finished with value: 5.3682190758184705 and parameters: {'model': 'RFR', 'n_estimators': 180, 'max_depth': 3, 'min_samples_split': 4, 'min_sample_leaf': 33, 'min_impurity_decrease': 0.08652687584646365}. Best is trial 0 with value: 5.3682190758184705.
[I 2026-06-26 17:35:03,568] Trial 1 finished with value: 5.384838771023379 and parameters: {'model': 'DTR', 'max_depth': 3, 'min_samples_split': 3, 'min_samples_float': 10, 'min_impurity_decrease': 0.0824313550289686}. Best is trial 0 with value: 5.3682190758184705.
[I 2026-06-26 17:35:12,753] Trial 2 finished with value: 4.507897588897153 and parameters: {'model': 'RFR', 'n_estimators': 225, 'max_depth': 5, 'min_samples_split': 5, 'min_sample_leaf': 18, 'min_impurity_decrease': 0.0741935816040961}. Best is trial 2 with value: 4.507897588897153.
[I 2026-06-26 17:35:18,892] Trial 3 finished with value: 3.2240375518798827 and parameters: {'model': 'XGBR', 'n_estimators': 171, 'max_depth': 5, 'learning_rate': 0.07971867082762552, 'min_child_weight': 3, 'sub_sample': 0.5585540005587115, 'colsample_bytree': 0.8336673308764336, 'gamma': 0.34910841966019623}. Best is trial 3 with value: 3.2240375518798827.
[I 2026-06-26 17:35:25,896] Trial 4 finished with value: 3.9266160570279522 and parameters: {'model': 'RFR', 'n_estimators': 108, 'max_depth': 7, 'min_samples_split': 5, 'min_sample_leaf': 20, 'min_impurity_decrease': 0.044167797198957776}. Best is trial 3 with value: 3.2240375518798827.
[I 2026-06-26 17:35:36,686] Trial 5 finished with value: 3.0674904325538264 and parameters: {'model': 'LGBMR', 'num_leaves': 38, 'min_child_samples': 21, 'max_depth': 13, 'learning_rate': 0.01425035415782891, 'subsample': 0.620234755497798, 'colsample_bytree': 0.9014558640424928, 'reg_alpha': 0.39652488465306623, 'reg_lambda': 0.2810528981564874}. Best is trial 5 with value: 3.0674904325538264.
[I 2026-06-26 17:35:42,821] Trial 6 finished with value: 3.243505430221558 and parameters: {'model': 'XGBR', 'n_estimators': 158, 'max_depth': 5, 'learning_rate': 0.06178100637244574, 'min_child_weight': 4, 'sub_sample': 0.5752931172272655, 'colsample_bytree': 0.959537006022527, 'gamma': 0.22674006195877033}. Best is trial 5 with value: 3.0674904325538264.
[I 2026-06-26 17:35:47,494] Trial 7 finished with value: 4.106092071533203 and parameters: {'model': 'XGBR', 'n_estimators': 101, 'max_depth': 2, 'learning_rate': 0.06143337586815488, 'min_child_weight': 6, 'sub_sample': 0.9595149173682744, 'colsample_bytree': 0.5762371638535216, 'gamma': 0.3749801812604301}. Best is trial 5 with value: 3.0674904325538264.
[I 2026-06-26 17:35:51,431] Trial 8 finished with value: 5.384838771023379 and parameters: {'model': 'DTR', 'max_depth': 3, 'min_samples_split': 5, 'min_samples_float': 34, 'min_impurity_decrease': 0.060103701213193125}. Best is trial 5 with value: 3.0674904325538264.
[I 2026-06-26 17:35:58,873] Trial 9 finished with value: 4.509801608365389 and parameters: {'model': 'RFR', 'n_estimators': 132, 'max_depth': 5, 'min_samples_split': 2, 'min_sample_leaf': 30, 'min_impurity_decrease': 0.04187862933735393}. Best is trial 5 with value: 3.0674904325538264.
[I 2026-06-26 17:36:07,794] Trial 10 finished with value: 3.3293408709859067 and parameters: {'model': 'LGBMR', 'num_leaves': 23, 'min_child_samples': 13, 'max_depth': 15, 'learning_rate': 0.011200098052261909, 'subsample': 0.5347896548673543, 'colsample_bytree': 0.5182771244382052, 'reg_alpha': 0.47499559622136156, 'reg_lambda': 0.06047535056407055}. Best is trial 5 with value: 3.0674904325538264.
[I 2026-06-26 17:36:16,282] Trial 11 finished with value: 3.080194029239828 and parameters: {'model': 'LGBMR', 'num_leaves': 65, 'min_child_samples': 35, 'max_depth': 11, 'learning_rate': 0.09255721929338394, 'subsample': 0.788309393081471, 'colsample_bytree': 0.8810517928730206, 'reg_alpha': 0.11217255127548781, 'reg_lambda': 0.5938488826023074}. Best is trial 5 with value: 3.0674904325538264.
[I 2026-06-26 17:36:24,217] Trial 12 finished with value: 3.043469216419491 and parameters: {'model': 'LGBMR', 'num_leaves': 54, 'min_child_samples': 29, 'max_depth': 12, 'learning_rate': 0.018997056389705794, 'subsample': 0.7139501997708919, 'colsample_bytree': 0.850010045231118, 'reg_alpha': 0.15912637594223772, 'reg_lambda': 0.45651029578933766}. Best is trial 12 with value: 3.043469216419491.
[I 2026-06-26 17:36:33,883] Trial 13 finished with value: 3.073463729978247 and parameters: {'model': 'LGBMR', 'num_leaves': 49, 'min_child_samples': 25, 'max_depth': 13, 'learning_rate': 0.012140628590934559, 'subsample': 0.6555757356442887, 'colsample_bytree': 0.7906995471565573, 'reg_alpha': 0.25765240236099735, 'reg_lambda': 0.386118295911582}. Best is trial 12 with value: 3.043469216419491.
[I 2026-06-26 17:36:42,628] Trial 14 finished with value: 3.067481966802162 and parameters: {'model': 'LGBMR', 'num_leaves': 43, 'min_child_samples': 25, 'max_depth': 10, 'learning_rate': 0.031180581688907565, 'subsample': 0.7266324104563645, 'colsample_bytree': 0.7216658074581209, 'reg_alpha': 0.9364270773234559, 'reg_lambda': 0.29658984370317065}. Best is trial 12 with value: 3.043469216419491.
[I 2026-06-26 17:36:50,694] Trial 15 finished with value: 3.0558233094923444 and parameters: {'model': 'LGBMR', 'num_leaves': 84, 'min_child_samples': 35, 'max_depth': 9, 'learning_rate': 0.03616572010481563, 'subsample': 0.839355278334025, 'colsample_bytree': 0.6999079827104984, 'reg_alpha': 0.9952441361002717, 'reg_lambda': 0.9856753433212518}. Best is trial 12 with value: 3.043469216419491.
[I 2026-06-26 17:36:59,124] Trial 16 finished with value: 3.0572647889387534 and parameters: {'model': 'LGBMR', 'num_leaves': 100, 'min_child_samples': 45, 'max_depth': 9, 'learning_rate': 0.0374859993410625, 'subsample': 0.9844704003158997, 'colsample_bytree': 0.6589090955149515, 'reg_alpha': 0.9881038366173287, 'reg_lambda': 0.9739046360520451}. Best is trial 12 with value: 3.043469216419491.
[I 2026-06-26 17:37:06,747] Trial 17 finished with value: 3.0686839170615072 and parameters: {'model': 'LGBMR', 'num_leaves': 83, 'min_child_samples': 37, 'max_depth': 8, 'learning_rate': 0.033153911397800676, 'subsample': 0.8600041329148284, 'colsample_bytree': 0.704177714355578, 'reg_alpha': 0.6730467448714234, 'reg_lambda': 0.9165930195290424}. Best is trial 12 with value: 3.043469216419491.
[I 2026-06-26 17:37:14,453] Trial 18 finished with value: 3.050073856040071 and parameters: {'model': 'LGBMR', 'num_leaves': 69, 'min_child_samples': 32, 'max_depth': 12, 'learning_rate': 0.04540176590409761, 'subsample': 0.8587651522867249, 'colsample_bytree': 0.7765543910550732, 'reg_alpha': 0.6855933284677846, 'reg_lambda': 0.6734829511564451}. Best is trial 12 with value: 3.043469216419491.
[I 2026-06-26 17:37:18,096] Trial 19 finished with value: 3.990792767662017 and parameters: {'model': 'DTR', 'max_depth': 7, 'min_samples_split': 2, 'min_samples_float': 50, 'min_impurity_decrease': 0.01724667622609706}. Best is trial 12 with value: 3.043469216419491.
[I 2026-06-26 17:37:25,202] Trial 20 finished with value: 3.0535135445124224 and parameters: {'model': 'LGBMR', 'num_leaves': 64, 'min_child_samples': 30, 'max_depth': 12, 'learning_rate': 0.0530611600128246, 'subsample': 0.9624032193775978, 'colsample_bytree': 0.7853139970477161, 'reg_alpha': 0.02616937192645502, 'reg_lambda': 0.6592875959580327}. Best is trial 12 with value: 3.043469216419491.
[I 2026-06-26 17:37:32,288] Trial 21 finished with value: 3.051756329730433 and parameters: {'model': 'LGBMR', 'num_leaves': 63, 'min_child_samples': 31, 'max_depth': 12, 'learning_rate': 0.05125020274699477, 'subsample': 0.9818777925217336, 'colsample_bytree': 0.7751695077264195, 'reg_alpha': 0.07675643294558465, 'reg_lambda': 0.6633021249732147}. Best is trial 12 with value: 3.043469216419491.
[I 2026-06-26 17:37:39,911] Trial 22 finished with value: 3.043322521421436 and parameters: {'model': 'LGBMR', 'num_leaves': 66, 'min_child_samples': 30, 'max_depth': 15, 'learning_rate': 0.04561190894548953, 'subsample': 0.8943674027500892, 'colsample_bytree': 0.7923107442273705, 'reg_alpha': 0.19857744918243836, 'reg_lambda': 0.6648650454701831}. Best is trial 22 with value: 3.043322521421436.
[I 2026-06-26 17:37:47,908] Trial 23 finished with value: 3.028206454699058 and parameters: {'model': 'LGBMR', 'num_leaves': 73, 'min_child_samples': 42, 'max_depth': 15, 'learning_rate': 0.024319639209201434, 'subsample': 0.8991453418106148, 'colsample_bytree': 0.8814531709186734, 'reg_alpha': 0.25082104860615473, 'reg_lambda': 0.4952374080087738}. Best is trial 23 with value: 3.028206454699058.
[I 2026-06-26 17:37:58,124] Trial 24 finished with value: 3.0179455374266917 and parameters: {'model': 'LGBMR', 'num_leaves': 80, 'min_child_samples': 50, 'max_depth': 15, 'learning_rate': 0.023519518787827508, 'subsample': 0.8936423248850214, 'colsample_bytree': 0.976499598546252, 'reg_alpha': 0.25899146208610646, 'reg_lambda': 0.4573958514937803}. Best is trial 24 with value: 3.0179455374266917.
[I 2026-06-26 17:38:08,369] Trial 25 finished with value: 3.0228820759560935 and parameters: {'model': 'LGBMR', 'num_leaves': 79, 'min_child_samples': 49, 'max_depth': 15, 'learning_rate': 0.026394969464884652, 'subsample': 0.9125770325520669, 'colsample_bytree': 0.9908885810623128, 'reg_alpha': 0.2934749253976703, 'reg_lambda': 0.5217219358006198}. Best is trial 24 with value: 3.0179455374266917.
[I 2026-06-26 17:38:16,930] Trial 26 finished with value: 3.0215029861328646 and parameters: {'model': 'LGBMR', 'num_leaves': 80, 'min_child_samples': 50, 'max_depth': 14, 'learning_rate': 0.02262849533704166, 'subsample': 0.9208806025223155, 'colsample_bytree': 0.9952572196716082, 'reg_alpha': 0.347650968870573, 'reg_lambda': 0.49879478629285934}. Best is trial 24 with value: 3.0179455374266917.
[I 2026-06-26 17:38:20,629] Trial 27 finished with value: 3.9740207494812103 and parameters: {'model': 'DTR', 'max_depth': 7, 'min_samples_split': 3, 'min_samples_float': 11, 'min_impurity_decrease': 0.02011996507188131}. Best is trial 24 with value: 3.0179455374266917.
[I 2026-06-26 17:38:26,605] Trial 28 finished with value: 3.0891629695892333 and parameters: {'model': 'XGBR', 'n_estimators': 290, 'max_depth': 7, 'learning_rate': 0.05327330563529713, 'min_child_weight': 10, 'sub_sample': 0.9759152380393916, 'colsample_bytree': 0.9998336615577884, 'gamma': 0.10188296395753654}. Best is trial 24 with value: 3.0179455374266917.
[I 2026-06-26 17:38:38,149] Trial 29 finished with value: 4.002708232130377 and parameters: {'model': 'RFR', 'n_estimators': 296, 'max_depth': 7, 'min_samples_split': 4, 'min_sample_leaf': 48, 'min_impurity_decrease': 0.0958792442676141}. Best is trial 24 with value: 3.0179455374266917.

best_params:  {'model': 'LGBMR', 'num_leaves': 80, 'min_child_samples': 50, 'max_depth': 15, 'learning_rate': 0.023519518787827508, 'subsample': 0.8936423248850214, 'colsample_bytree': 0.976499598546252, 'reg_alpha': 0.25899146208610646, 'reg_lambda': 0.4573958514937803}
best value:  3.0179455374266917

2026/06/26 17:38:53 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

training mean absolute error:  2.766272790879201
testing mean absolute error:  3.0473665143248385
training r2_score:  0.8656284357744775
testing r2_score 0.8363944578500242
🏃 View run regressor models with hyperparameters tunning at: https://dagshub.com/akashkangule18/SWIGGI-DELIVERY-TIME-PREDICTION.mlflow/#/experiments/7/runs/8d5d34f3714c4ea2845959e7b3f712dd
🧪 View experiment at: https://dagshub.com/akashkangule18/SWIGGI-DELIVERY-TIME-PREDICTION.mlflow/#/experiments/7

In [70]:
print(study.best_params)
print(final_model.get_params())

{'model': 'LGBMR', 'num_leaves': 57, 'min_child_samples': 37, 'max_depth': 12, 'learning_rate': 0.017373774402495844, 'subsample': 0.9628514766056495, 'colsample_bytree': 0.8712435268087318, 'reg_alpha': 0.21226851924030313, 'reg_lambda': 0.767911464391989}
{'boosting_type': 'gbdt', 'class_weight': None, 'colsample_bytree': 0.9490736779783902, 'importance_type': 'split', 'learning_rate': 0.012231948787586006, 'max_depth': 15, 'min_child_samples': 10, 'min_child_weight': 0.001, 'min_split_gain': 0.0, 'n_estimators': 100, 'n_jobs': None, 'num_leaves': 100, 'objective': None, 'random_state': None, 'reg_alpha': 0.9659772138867988, 'reg_lambda': 0.009653096582090622, 'subsample': 0.5052035303001198, 'subsample_for_bin': 200000, 'subsample_freq': 0}

In [69]:
scores = cross_val_score(
    LGRregressor,
    X_train,
    y_train,
    cv=5,
    scoring="neg_mean_absolute_error"
)

print(-scores.mean())

3.746923263629184